src/cms/urls.py
from django.urls import path

from cms.views import AboutView, LegalNoticeView, PrivacyPolicyView

app_name = 'cms'

urlpatterns = [
    path('about-us/', AboutView.as_view(), name='about-us'),
    path('legal-notice/', LegalNoticeView.as_view(), name='legal-notice'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy-policy'),
]

src/equipments/urls.py
# -*- coding: utf-8 -*-
from django.urls import path, re_path

from .views.activity import ActivityDetailView
from .views.institution import (InstitutionPublicDetailView,
                                FavoriteEquipments,
                                FavoriteInstitutions,
                                CommentedInstitutions,
                                EquipmentPublicDetailView,
                                InstitutionPhotoUploadView,
                                EquipmentPhotoUploadView)
from .views.search import SearchView

app_name = 'equipments'

urlpatterns = [

    re_path(r'activities/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$',
            ActivityDetailView.as_view(),
            name='activity-details'),

    re_path(r'institutions/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', InstitutionPublicDetailView.as_view(),
            name='institution-details'),

    re_path(r'equipments/(?P<pk>[0-9]+)/(?P<slug>[-\w]+)/$', EquipmentPublicDetailView.as_view(),
            name='equipment-details'),

    path('institutions/favorites/', FavoriteInstitutions.as_view(), name='institutions-favorites'),
    path('equipments/favorites/', FavoriteEquipments.as_view(), name='equipments-favorites'),
    path('institutions/commented/', CommentedInstitutions.as_view(), name='institutions-commented'),

    path('search/', SearchView.as_view(), name='search'),

    re_path(
        r'^(?P<pk>\d+)/institution-upload/$',
        view=InstitutionPhotoUploadView.as_view(),
        name='institution_photo_upload_view',
    ),

    re_path(
        r'^(?P<pk>\d+)/equipment-upload/$',
        view=EquipmentPhotoUploadView.as_view(),
        name='equipment_photo_upload_view',
    ),
]

src/equipments/models/base.py
from core.models.abstracts import ActivatedAbstractModel, SluggedAbstractModel, TimeStampedAbstractModel


class GenericAbstractModel(ActivatedAbstractModel, SluggedAbstractModel, TimeStampedAbstractModel):
    class Meta:
        abstract = True

    def __str__(self):
        return self.label

src/equipments/models/locations.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


from .base import GenericAbstractModel


class Department(GenericAbstractModel):
    class Meta:
        verbose_name = _('département')
        verbose_name_plural = _('départements')
        ordering = ('label',)

    code = models.CharField(_('code département'), max_length=4, unique=True)


class Commune(GenericAbstractModel):
    class Meta:
        verbose_name = _('commune')
        verbose_name_plural = _('communes')
        ordering = ('label',)

    code_insee = models.CharField(_('code INSEE'), max_length=6, unique=True)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='communes')

src/equipments/models/socials.py
from publishing.models.publishing import Rate


class GlobalRate(Rate):
    pass


class HygieneRate(Rate):
    pass


class ServicesRate(Rate):
    pass


class EquipmentsRate(Rate):
    pass

src/equipments/forms/activity.py
# -*- coding: utf-8 -*-
from django import forms

from equipments.models.categories import Activity


class MultiSelectActivitiesForm(forms.Form):

    activities = forms.ModelMultipleChoiceField(widget=forms.SelectMultiple(),
                                                queryset=Activity.objects.filter(is_active=True).order_by('label'))


class MultiCheckboxActivitiesForm(forms.Form):

    activities = forms.ModelMultipleChoiceField(widget=forms.CheckboxSelectMultiple(),
                                                queryset=Activity.objects.filter(is_active=True).order_by('label'))

src/equipments/forms/socials.py
from publishing.forms.rating import RatingForm
from equipments.models.socials import GlobalRate, HygieneRate, ServicesRate, EquipmentsRate


# class GlobalRatingForm(RatingForm):
#     class Meta:
#         model = GlobalRate
#
#
# class HygieneRatingForm(RatingForm):
#     class Meta:
#         model = HygieneRate
#
#
# class ServicesRatingForm(RatingForm):
#     class Meta:
#         model = ServicesRate
#
#
# class EquipmentsRatingForm(RatingForm):
#     class Meta:
#         model = EquipmentsRate
#

src/equipments/views/activity.py
# -*- coding: utf-8 -*-
from django.views.generic import ListView, DetailView

from equipments.models.categories import Activity
from equipments.forms.activity import MultiSelectActivitiesForm

from cms.models.cms import Slide


class ActivityListView(ListView):

    model = Activity
    template_name = 'equipments/partial/activities.html'

    paginate_by = 6

    def get_queryset(self):
        return Activity.objects.filter(is_active=True)

    def get_context_data(self, **kwargs):
        context = super(ActivityListView, self).get_context_data(**kwargs)
        context['slides'] = Slide.objects.all()
        context['form_activities'] = MultiSelectActivitiesForm
        return context


class ActivityDetailView(DetailView):

    model = Activity
    template_name = 'site/activity-detail.html'

src/equipments/views/institution.py
# -*- coding: utf-8 -*-
from django.views.generic import View

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.shortcuts import redirect
from django.utils.decorators import method_decorator
from django.views.generic import DetailView, ListView

from equipments.models.categories import Activity
from equipments.models.equipment import Equipment
from equipments.models.institution import Institution
from equipments.models.socials import GlobalRate, HygieneRate, EquipmentsRate, ServicesRate
from publishing.models.publishing import Comment, Favorite
from publishing.forms.comment import CreateCommentForm
# from equipments.forms.socials import GlobalRatingForm, HygieneRatingForm, EquipmentsRatingForm, ServicesRatingForm

from braces.views import (AjaxResponseMixin, JSONResponseMixin)

from core.models.attachement import AttachedMedia


class InstitutionPhotoUploadView(JSONResponseMixin, AjaxResponseMixin, View):

    def post_ajax(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            error_dict = {'message': 'Only logged in users can upload files.'}
            return self.render_json_response(error_dict, status=401)
        try:
            institution = Institution.objects.get(pk=kwargs.get('pk'))
        except Institution.DoesNotExist:
            error_dict = {'message': 'Institution not found.'}
            return self.render_json_response(error_dict, status=404)
        uploaded_file = request.FILES['file']
        AttachedMedia.objects.create(
            image=uploaded_file,
            content_type=ContentType.objects.get_for_model(institution),
            object_id=institution.pk,
        )
        response_dict = {
            'message': 'File uploaded successfully!',
        }
        return self.render_json_response(response_dict, status=200)


class EquipmentPhotoUploadView(JSONResponseMixin, AjaxResponseMixin, View):

    def post_ajax(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            error_dict = {'message': 'Unauthorized.'}
            return self.render_json_response(error_dict, status=401)
        try:
            equipment = Equipment.objects.get(pk=kwargs.get('pk'))
        except Equipment.DoesNotExist:
            error_dict = {'message': 'Equipment not found.'}
            return self.render_json_response(error_dict, status=404)
        uploaded_file = request.FILES['file']
        AttachedMedia.objects.create(
            image=uploaded_file,
            content_type=ContentType.objects.get_for_model(equipment),
            object_id=equipment.pk,
        )
        response_dict = {
            'message': 'File uploaded successfully!',
        }
        return self.render_json_response(response_dict, status=200)


class EquipmentPublicDetailView(DetailView):
    model = Equipment
    template_name = 'equipments/equipment-public.html'

    def get_context_data(self, **kwargs):
        context = super(EquipmentPublicDetailView, self).get_context_data(**kwargs)
        context['form_comment'] = CreateCommentForm
        context['activities'] = Activity.objects.filter(disciplines__equipments=context['equipment']).distinct()
        # context['activities'] = context['equipment'].disciplines.activity.distinct()
        return context

    @method_decorator(login_required)
    def post(self, request, pk, slug):
        # post = Post.objects.get(institution=self.get_object())
        obj = self.get_object()
        comment = Comment(
            publisher=request.user,
            content_type=ContentType.objects.get_for_model(obj),
            object_id=obj.pk,
        )

        if request.POST['global-rate'] and int(request.POST['global-rate']) > 0:
            global_rating = GlobalRate(
                publisher=request.user,
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.pk,
                rating=request.POST['global-rate'],
            )
            global_rating.save()

        if request.POST['hygiene-rate'] and int(request.POST['hygiene-rate']) > 0:
            hygiene_rating = HygieneRate(
                publisher=request.user,
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.pk,
                rating=request.POST['hygiene-rate'],
            )
            hygiene_rating.save()

        if request.POST['services-rate'] and int(request.POST['services-rate']) > 0:
            services_rating = ServicesRate(
                publisher=request.user,
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.pk,
                rating=request.POST['services-rate'],
            )
            services_rating.save()

        if request.POST['equipments-rate'] and int(request.POST['equipments-rate']) > 0:
            equipments_rating = EquipmentsRate(
                publisher=request.user,
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.pk,
                rating=request.POST['equipments-rate'],
            )
            equipments_rating.save()

        comment_form = CreateCommentForm(request.POST, instance=comment)
        if comment_form.is_valid():
            comment_form.save()
        return redirect(self.get_success_url())

    def get_success_url(self):
        return self.get_object().get_absolute_url()


class InstitutionPublicDetailView(DetailView):
    model = Institution
    template_name = 'equipments/institution-public.html'

    def get_context_data(self, **kwargs):
        context = super(InstitutionPublicDetailView, self).get_context_data(**kwargs)
        # TODO only active equipments
        context['equipments'] = context['institution'] \
            .equipments.filter(disciplines__is_active=True) \
            .distinct()
        context['form_comment'] = CreateCommentForm
        return context

    @method_decorator(login_required)
    def post(self, request, pk, slug):
        # post = Post.objects.get(institution=self.get_object())
        obj = self.get_object()
        comment = Comment(
            publisher=request.user,
            content_type=ContentType.objects.get_for_model(obj),
            object_id=obj.pk,
        )
        if request.POST['global-rate'] and int(request.POST['global-rate']) > 0:
            global_rating = GlobalRate(
                publisher=request.user,
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.pk,
                rating=request.POST['global-rate'],
            )
            global_rating.save()

        if request.POST['hygiene-rate'] and int(request.POST['hygiene-rate']) > 0:
            hygiene_rating = HygieneRate(
                publisher=request.user,
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.pk,
                rating=request.POST['hygiene-rate'],
            )
            hygiene_rating.save()

        if request.POST['services-rate'] and int(request.POST['services-rate']) > 0:
            services_rating = ServicesRate(
                publisher=request.user,
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.pk,
                rating=request.POST['services-rate'],
            )
            services_rating.save()

        if request.POST['equipments-rate'] and int(request.POST['equipments-rate']) > 0:
            equipments_rating = EquipmentsRate(
                publisher=request.user,
                content_type=ContentType.objects.get_for_model(obj),
                object_id=obj.pk,
                rating=request.POST['equipments-rate'],
            )
            equipments_rating.save()

        comment_form = CreateCommentForm(request.POST, instance=comment)

        # global_rating_form = GlobalRatingForm(request.POST, instance=global_rating)
        # hygiene_rating = HygieneRatingForm(request.POST, instance=hygiene_rating)
        # services_rating_form = ServicesRatingForm(ratingrequest.POST, instance=services_rating)
        # equipments_rating_form = EquipmentsRatingForm(request.POST, instance=equipments_rating)

        if comment_form.is_valid():
            comment_form.save()

        # if global_rating_form.is_valid(): global_rating_form.save()
        # if hygiene_rating.is_valid(): hygiene_rating.save()
        # if services_rating_form.is_valid(): services_rating_form.save()
        # if equipments_rating_form.is_valid(): equipments_rating_form.save()

        return redirect(self.get_success_url())

    def get_success_url(self):
        return self.get_object().get_absolute_url()


class FavoriteInstitutions(LoginRequiredMixin, ListView):
    model = Institution
    template_name = 'equipments/institutions-list.html'

    def get_queryset(self):
        # favorites = Favorite.objects.filter(publisher=self.request.user)
        return Institution.objects.filter(
            favorites__in=Favorite.objects.filter(publisher=self.request.user)
        ).distinct()


class FavoriteEquipments(LoginRequiredMixin, ListView):
    model = Equipment
    template_name = 'equipments/equipments-list.html'

    def get_queryset(self):
        # favorites = Favorite.objects.filter(publisher=self.request.user)
        return Equipment.objects.filter(
            favorites__in=Favorite.objects.filter(publisher=self.request.user)
        ).distinct()


class CommentedInstitutions(LoginRequiredMixin, ListView):
    model = Institution
    template_name = 'equipments/institutions-list.html'

    def get_queryset(self):
        return Institution.objects.filter(
            comments__in=Comment.objects.filter(publisher=self.request.user, )
        ).distinct()

src/equipments/views/search.py
# -*- coding: utf-8 -*-
from django.shortcuts import redirect
from django.views.generic import TemplateView
from equipments.forms.activity import MultiCheckboxActivitiesForm
from equipments.models.categories import Activity


class SearchView(TemplateView):

    template_name = 'search/search.html'

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['form_activities'] = MultiCheckboxActivitiesForm
        return context

    def get(self, request, *args, **kwargs):
        if request.GET.get('previous') == '/':
            filters = dict(request.GET)
            if 'activities' in filters:
                activities = filters['activities']
                if len(activities) == 1:
                    activity = Activity.objects.get(pk=activities[0])
                    return redirect(activity.get_absolute_url())
        return super(SearchView, self).get(request, *args, **kwargs)

src/equipments/templates/site/activity-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ activity.label }}{% endblock %}

{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/range.css' %}">
    <link rel="stylesheet" href="{% static 'css/progressbar.css' %}">
    <link href='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.css' rel='stylesheet'/>
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.mapbox.css'
          rel='stylesheet'/>
    <!--[if lt IE 9]>
    <link href='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.ie.css' rel='stylesheet' />
    <![endif]-->
    <link href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css' rel='stylesheet'/>

{% endblock %}

{% block content %}
    <div class="progress-bar" id="progress-bar"></div>
    <header class="background-cover"
            style="background-image: url('{% if activity.image %}{{ activity.image.url }}{% else %}{% static 'img/placeholder@l.png' %}{% endif %}')">
    <div class="uk-overlay uk-light uk-container">
            <input name="activity-id" id="activityId" value="{{ activity.pk }}" hidden>
            <h1 class="uk-article-title">{{ activity.label }}</h1>
            {% if activity.description %}
            <h4>Description</h4>
                <p class="uk-text-justify">{{ activity.description }}</p>
            {% endif %}
        </div>
    </header>

    <section class="uk-container elements-details">
        <article class="uk-article">

            <form method="get" action="">

                <div class="uk-margin-bottom uk-width-1-1">
                    <input class="uk-input uk-margin-small-top" type="search" id="address-search"
                           placeholder="Rechercher un lieu..."/>
                </div>

                <div id="advanced-search" hidden>
                    <div class="uk-divider-icon"></div>
                    <div class="uk-margin-bottom uk-grid-small uk-child-width-1-2@s uk-grid" uk-grid>
                        <div class="uk-width-1-1">
                            <label><i>Type du lieu</i></label>
                        </div>

                        <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
                            <label><input class="uk-radio" id="not_defined" type="radio" name="is_public" value="None" checked> Tous</label>
                            <label><input class="uk-radio" id="is_public" type="radio" name="is_public" value="True"> Publique</label>
                            <label><input class="uk-radio" id="is_private" type="radio" name="is_public" value="False"> Privé</label>
                        </div>

                    </div>
                    <div class="uk-divider-icon"></div>
                    <div class="uk-margin-bottom uk-grid-small uk-child-width-1-2@s uk-grid" uk-grid>
                        <div class="uk-width-1-1">
                            <label><i>Disciplines spotives</i></label>
                        </div>
                        {% for discipline in activity.sports_disciplines.all %}
                            <label>
                                <input class="uk-checkbox"
                                       type="checkbox"
                                       name="disciplines"
                                       value="{{ discipline.pk }}"
                                       id="discipline_{{ discipline.pk }}">
                                {{ discipline.label }}
                            </label>
                        {% endfor %}
                    </div>
                    <div class="uk-divider-icon"></div>
                    <div class="uk-grid uk-child-width-1-2@s uk-padding-top" uk-grid>
                        <div class="uk-margin uk-width-1-1">
                            <div class="range-slider">
                                <label for="lat-search"><i>Distance de recherche (KM)</i></label>
                                <input class="range-slider__range" name="distance" id="distance-search"
                                       type="range" value="3" min="1" max="25">
                                <span class="range-slider__value">0</span>
                            </div>
                        </div>
                        <div class="uk-margin uk-hidden">
                            <label for="lng-search">Langitude</label>
                            <input class="uk-input uk-disabled" name="lng" type="search" id="lng-search"
                                   placeholder="Langitude"/>
                        </div>
                        <div class="uk-margin uk-hidden">
                            <label for="lat-search">Latitude</label>
                            <input class="uk-input uk-disabled" name="lat" type="search" id="lat-search"
                                   placeholder="Latitude"/>
                        </div>
                    </div>
                </div>

                <div class="uk-clearfix">
                    <div class="uk-float-right">
                        <button class="uk-button uk-button-default uk-margin-small-bottom"
                                uk-toggle="target: #advanced-search; animation: uk-animation-fade">recherche avancée
                        </button>
                        <input type="submit" value="Rechercher"
                               class="uk-button uk-button-primary uk-margin-small-bottom">
                    </div>
                </div>
            </form>
        </article>
    </section>

    <div class="uk-visible@m">
        <div class="black-separator"></div>
        <div class="uk-child-width-1-5 uk-grid-small uk-background-muted" data-sticky-container uk-grid>
            <div class="uk-container uk-width-3-5 map-elements-container" id="map-elements-container">
                <div class="uk-child-width-1-2@m uk-grid-small uk-grid-match map-elements" id="map-elements" uk-grid>
                    <!-- -->
                    <div class="uk-width-1-1">
                        <p>Merci de patienter</p>
                        <div class="spinner-container uk-background-muted">
                            <a class="infinite-more-link" href="#" style="display: block;"
                               uk-spinner></a>
                        </div>
                    </div>
                    <!-- -->
                </div>
            </div>
            <div class="uk-width-2-5 map-container sticky-map" id="map-container" style="position: sticky; top: 80px">
                <div id='map'></div>
            </div>
        </div>

        <div id="map-control">
            <a href="#" class="uk-icon-link" uk-icon="icon: chevron-right; ratio: 1.5" id="toggle-elements"></a>
            <a href="#" class="uk-icon-link" uk-icon="icon: chevron-left; ratio: 1.5" id="toggle-map"></a>
        </div>

        <div class="black-separator" id="bottom-scroll-spy"></div>
    </div>

    <div class="uk-hidden@m">
        <ul class="uk-child-width-expand" style="margin-bottom: 0" uk-tab>
            <li class="uk-active"><a href="#">Carte</a></li>
            <li><a href="#">Liste</a></li>
        </ul>
        <ul class="uk-switcher">
            <li>
                <div id='map2' style="height: 100vh; width: 100vw"></div>
            </li>
            <li>
                <div class="uk-container map-elements-container" id="map-elements-container2">
                <div class="uk-child-width-1-2@m uk-grid-small uk-grid-match map-elements" id="map-elements2" uk-grid>
                    <!-- -->
                    <div class="uk-width-1-1">
                        <p>Merci de patienter</p>
                        <div class="spinner-container uk-background-muted">
                            <a class="infinite-more-link" href="#" style="display: block;"
                               uk-spinner></a>
                        </div>
                    </div>
                    <!-- -->
                </div>
            </div>
            </li>
        </ul>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src='https://api.mapbox.com/mapbox.js/v3.1.1/mapbox.js'></script>
    <script src='https://api.mapbox.com/mapbox.js/plugins/leaflet-locatecontrol/v0.43.0/L.Control.Locate.min.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>

    <script src="{% static 'js/range.js' %}"></script>
    <script src="{% static 'js/institutions-map.js' %}"></script>
{% endblock %}

src/equipments/templates/site/home.html
{% extends 'base.html' %}
{% load static class_tags %}

{% block title %}Page d'accueil{% endblock %}

{% block styles %}
    {{ block.super }}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.4/dist/css/select2.min.css" rel="stylesheet"/>
{% endblock %}

{% block content %}

    <header class="hero uk-position-relative uk-visible-toggle uk-light" id="hero"
            uk-slideshow="autoplay: true; autoplay-interval: 4000; ratio: false">

        <ul class="uk-slideshow-items">

            {% if slides %}
                {% for slide in slides %}
                    <li>
                        <img data-src="{{ slide.image.large.url }}" class="lazy" alt="{{ slide.text }}" uk-cover>
                        <div class="uk-position-center uk-panel"><h1 style="padding: 20vh">{{ slide.text }}</h1></div>
                    </li>

                {% endfor %}
            {% else %}

                <li><img data-src="{% static 'img/home/basket.png' %}" class="lazy" alt="basket" uk-cover></li>
                <li><img data-src="{% static 'img/home/football.png' %}" class="lazy" alt="football" uk-cover></li>
                <li><img data-src="{% static 'img/home/golf.png' %}" class="lazy" alt="golf" uk-cover></li>
                <li><img data-src="{% static 'img/home/tennis.png' %}" class="lazy" alt="tennis" uk-cover></li>
                <li><img data-src="{% static 'img/home/skate.png' %}" class="lazy" alt="skate" uk-cover></li>
                <li><img data-src="{% static 'img/home/badminton.png' %}" class="lazy" alt="badminton" uk-cover></li>
            {% endif %}
        </ul>

        <a class="uk-position-center-left uk-position-small uk-hidden-hover" href="#"
           uk-slidenav-previous uk-slideshow-item="previous"></a>
        <a class="uk-position-center-right uk-position-small uk-hidden-hover" href="#"
           uk-slidenav-next uk-slideshow-item="next"></a>
        <div class="uk-position-bottom uk-position-medium uk-text-center uk-light">

            {% if not slides %}
                <h1 class="uk-text-center" style="color: #f8f8f8">
                    <i uk-icon="icon: search; ratio: 2"></i> Je cherche un terrain de
                    <span class="txt-rotate"
                          data-period="2000"
                          data-rotate='[ "Basket", "Football", "Golf", "Tennis", "Skate" , "Badminton" ]'></span>
                </h1>

            {% endif %}
            <a href="#activities" class="uk-align-center uk-button uk-width-1-2@s button-orange"
               uk-scroll="offset:80">
                <span class="uk-margin-small-right" uk-icon="icon: thumbnails"></span>
                Afficher toutes les activités
            </a>
        </div>
    </header>

    <div class="black-separator"></div>

    {% include 'equipments/partial/activities.html' %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.2.1/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/waypoints@4.0.1/lib/jquery.waypoints.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/waypoints@4.0.1/lib/shortcuts/infinite.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.4/dist/js/select2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/lazyload@2.0.0-beta.2/lazyload.js"></script>
    <script>

        window.addEventListener("load", function () {
            window.cookieconsent.initialise({
                "palette": {
                    "popup": {
                        "background": "#eaf7f7",
                        "text": "#5c7291"
                    },
                    "button": {
                        "background": "#56cbdb",
                        "text": "#ffffff"
                    }
                },
                "content": {
                    "message": "Ce site utilise des cookies pour vous assurer la meilleure expérience sur notre site.",
                    "dismiss": "Je comprends",
                    "link": "En savoir plus",
                    "href": "https://www.kojump.fr/legal/privacy-policy/"
                }
            })
        });

        // Lazy loading images slider
        var images = document.querySelectorAll(".lazy");
        var lazy = new lazyload(images);
        lazy.loadImages();

        $(document).ready(function () {
            var infinite = new Waypoint.Infinite({
                element: $('.infinite-container')[0],
                onBeforePageLoad: function () {
                    $('.infinite-more-link').show();
                },
                onAfterPageLoad: function ($items) {
                    $('.infinite-more-link').hide();
                }
            });
        });

        $('#id_activities').select2();
    </script>
{% endblock %}