src/cms/urls.py
from django.urls import path

from cms.views import AboutView, LegalNoticeView, PrivacyPolicyView

app_name = 'cms'

urlpatterns = [
    path('about-us/', AboutView.as_view(), name='about-us'),
    path('legal-notice/', LegalNoticeView.as_view(), name='legal-notice'),
    path('privacy-policy/', PrivacyPolicyView.as_view(), name='privacy-policy'),
]

src/publishing/urls.py
# -*- coding: utf-8 -*-
from django.urls import re_path, path

from .views.favorite import json_set_favorite
from .views.comment import CommentOwnerListView


app_name = 'publishing'

urlpatterns = [
    re_path(r'likes/(?P<content_type_id>[^/]+)/(?P<object_id>[^/]+)/$', json_set_favorite, name='json_set_favorite'),
    path('comments/', CommentOwnerListView.as_view(), name='comments-list'),
]

src/publishing/models/abstracts.py
from django.core.exceptions import PermissionDenied
from django.db import models
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import User

from core.models.abstracts import ActivatedAbstractModel, TimeStampedAbstractModel


class ModeratedManager(models.Manager):
    def get_queryset(self):
        return super(ModeratedManager, self).get_queryset().filter(status='YES')


class NotModeratedManager(models.Manager):
    def get_queryset(self):
        return super(NotModeratedManager, self).get_queryset().filter(status='NO')


class PostableManager(models.Manager):
    def get_queryset(self, user):
        return super(PostableManager, self).get_queryset().filter(publisher=user)


class ModeratedAbstractModel(models.Model):
    STATUS = (
        ('NO', _('non modéré')),
        ('YES', _('modéré')),
    )

    class Meta:
        abstract = True

    status = models.CharField(_('statut'), max_length=3, choices=STATUS, default='NO')

    objects = models.Manager()
    moderated = ModeratedManager()
    not_moderated = NotModeratedManager()


class PostableAbstractModel(ActivatedAbstractModel, TimeStampedAbstractModel):
    class Meta:
        abstract = True

    publisher = models.ForeignKey(User, null=True, blank=True, on_delete=models.SET_NULL)

    def set_publisher(self, user):
        if not user:
            raise PermissionDenied
        self.publisher = user

    objects = models.Manager()
    publications = PostableManager()

src/publishing/models/publishing.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from core.models.abstracts import GenericRelationAbstractModel

from .abstracts import ModeratedAbstractModel, PostableAbstractModel


class Comment(GenericRelationAbstractModel, ModeratedAbstractModel, PostableAbstractModel):
    class Meta:
        verbose_name = _('commentaire')
        verbose_name_plural = _('commentaires')

    comment = models.TextField(_('commentaire'))

    def __str__(self):
        return self.comment


class Favorite(GenericRelationAbstractModel, PostableAbstractModel):
    class Meta:
        verbose_name = _('favori')
        verbose_name_plural = _('favoris')

    def __str__(self):
        return self.publisher.username


class Rate(GenericRelationAbstractModel, PostableAbstractModel):
    RATING_CHOICES = (
        (1, _('très mauvais')),
        (2, _('mauvais')),
        (3, _('moyen')),
        (4, _('bon')),
        (5, _('très bon')),
    )

    class Meta:
        verbose_name = _('note')
        verbose_name_plural = _('notes')

    rating = models.IntegerField(_('note'), choices=RATING_CHOICES)

    def __str__(self):
        return self.get_rating_display()


class UserRequest(GenericRelationAbstractModel, PostableAbstractModel):

    STATUS_CHOICE = (
        ('WAITING', _('en attente')),
        ('TREATED', _('traitée')),
        ('FAILURE', _('refusée')),
    )

    SUBJECT_CATEGORIES = (
        ('PROPERTY', _('changement de propriétaire')),
        ('CLAIM', _('réclamation')),
        ('OTHERS', _('autres')),
    )

    REQUEST_OBJECT = (
        ('INSTITUTION', _('institution sportive')),
    )

    class Meta:
        verbose_name = _('requête utilisateur')
        verbose_name_plural = _('requêtes utilisateurs')

    subject = models.CharField(_('sujet'), max_length=100)
    content = models.TextField(_('conten'))
    status = models.CharField(_('statut'), max_length=7, choices=STATUS_CHOICE, default='WAITING')
    category = models.CharField(_('catégorie'), max_length=8, choices=SUBJECT_CATEGORIES, default='PROPERTY')
    obj = models.CharField(_('objet'), max_length=14, choices=REQUEST_OBJECT, default='INSTITUTION')

    def __str__(self):
        return self.subject

src/publishing/forms/comment.py
# -*- coding: utf-8 -*-
from django.utils.translation import ugettext_lazy as _
from django import forms

from publishing.models.publishing import Comment


class CreateCommentForm(forms.ModelForm):

    comment = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': _(u'Ecrire un commentaire...'), 'rows': '5'}))

    class Meta:
        model = Comment
        fields = ['comment']

src/publishing/forms/rating.py
# -*- coding: utf-8 -*-
from django import forms

from publishing.models.publishing import Rate


class RatingForm(forms.ModelForm):
    rating = forms.IntegerField(max_value=5, min_value=1)

    class Meta:
        model = Rate
        fields = ['rating']

src/publishing/views.py
from django.shortcuts import render

# Create your views here.

src/publishing/views/comment.py
from django.views.generic import ListView

from django.contrib.auth.mixins import LoginRequiredMixin

from publishing.models.publishing import Comment


class CommentOwnerListView(LoginRequiredMixin, ListView):

    model = Comment
    template_name = 'publishing/comments-list.html'

    def get_queryset(self):
        return Comment.objects.filter(publisher=self.request.user).distinct()

src/publishing/views/favorite.py
import json

from django.http import HttpResponse
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_exempt

from django.contrib.contenttypes.models import ContentType

from publishing.models.publishing import Favorite
from publishing.templatetags.favorites_tags import get_favorites_count


@never_cache
@csrf_exempt
def json_set_favorite(request, content_type_id, object_id):
    """
    Set the object as favorite for the current user
    """
    result = {
        'success': False,
    }
    if request.user.is_authenticated and request.method == 'POST':
        content_type = ContentType.objects.get(id=content_type_id)
        obj = content_type.get_object_for_this_type(pk=object_id)
        favorite, is_created = Favorite.objects.get_or_create(
            content_type=ContentType.objects.get_for_model(obj),
            object_id=obj.id,
            publisher=request.user
        )
        if not is_created:
            favorite.delete()
        result = {
            'success': True,
            'obj': obj.label,
            'action': is_created and 'added' or 'removed',
            'count': get_favorites_count(obj)
        }
    data = json.dumps(result, ensure_ascii=False)
    return HttpResponse(data)

src/publishing/templates/publishing/includes/favorite.html
{% load i18n %}

<div class="like-widget uk-text-right@s">
    <button id="like-button"
            class="uk-button uk-button-default uk-button-small like-button"
            data-href="{% url "publishing:json_set_favorite" content_type_id=content_type_id object_id=object.pk %}"
            data-unlike-text="{% trans "Ajouter au favories" %}"
            data-like-text="{% trans "J'aime ce lieu" %}">
        <span id="favorite-icon" class="{% if is_user_favorite %}favorite-active{% endif %}"
              uk-icon="icon: heart"></span>
        <small id="like-btn-txt">{% if is_user_favorite %}J'aime ce lieu{% else %}Ajouter au favories{% endif %}</small>
    </button>
    <br>
    <small style="margin-right: 5px"><span id="like-badge" class="like-badge badge">{{ count }}</span> personnes aiment
        ce lieu
    </small>
</div>
<script>
    (function ($) {

        var likeWidget = document.getElementById('like-button');
        var likeIcon = document.getElementById('favorite-icon');
        var likeBadge = document.getElementById('like-badge');
        var likeBtnTxt = document.getElementById('like-btn-txt');

        likeWidget.addEventListener('click', function (e) {
            axios.post(likeWidget.getAttribute('data-href'))
                .then(function (response) {
                    if (response.data.action === 'added') {
                        likeIcon.classList.add("favorite-active");
                        likeBtnTxt.innerHTML = likeWidget.getAttribute('data-like-text')
                    } else {
                        likeIcon.classList.remove("favorite-active");
                        likeBtnTxt.innerHTML = likeWidget.getAttribute('data-unlike-text')
                    }
                    likeBadge.innerHTML = response.data.count;
                })
                .catch(function (error) {
                    console.log(error);
                });
        })
    })();
</script>